version: 0.2

phases:
  pre_build:
    commands:
      - echo Loggeando a ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_ID
      - TAG="$(date +%Y%m%d%H%M%S)"  
  build:
    commands:
      - set -e  #corte en cualquier falla
      - echo Build del dia `date`
      - echo Building Docker image...
      - docker build -t $REPO_NAME .
      - docker tag --force $REPO_NAME:latest $AWS_ECR_ID/$REPO_NAME:$TAG
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $AWS_ECR_ID/$REPO_NAME:$TAG
