version: 0.2

phases:
  pre_build:
    commands:
      - echo Loggeando a ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 037380703489.dkr.ecr.us-east-2.amazonaws.com
      - echo Creando ECR repository ...
      - aws ecr describe-repositories --repository-names my-docker-app || aws ecr create-repository --repository-name my-docker-app
      - TAG=$(date +%Y%m%d%H%M%S)  # Generate timestamp-based tag
  build:
    commands:
      - echo Build del dia `date`
      - echo Building Docker image...
      - docker build -t my-docker-app:$TAG .
      - docker tag my-docker-app:$TAG 037380703489.dkr.ecr.us-east-2.amazonaws.com/my-docker-app:$TAG
      - docker tag my-docker-app:$TAG 037380703489.dkr.ecr.us-east-2.amazonaws.com/my-docker-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 037380703489.dkr.ecr.us-east-2.amazonaws.com/my-docker-app:$TAG
      - docker push 037380703489.dkr.ecr.us-east-2.amazonaws.com/my-docker-app:latest
